# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andre/D3-driver-drownsiness-detection-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andre/D3-driver-drownsiness-detection-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andre/D3-driver-drownsiness-detection-master/CMakeFiles /home/andre/D3-driver-drownsiness-detection-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andre/D3-driver-drownsiness-detection-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named d3.elf

# Build rule for target.
d3.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 d3.elf
.PHONY : d3.elf

# fast build rule for target.
d3.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/build
.PHONY : d3.elf/fast

CBluetoothCom.o: CBluetoothCom.cpp.o
.PHONY : CBluetoothCom.o

# target to build an object file
CBluetoothCom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/CBluetoothCom.cpp.o
.PHONY : CBluetoothCom.cpp.o

CBluetoothCom.i: CBluetoothCom.cpp.i
.PHONY : CBluetoothCom.i

# target to preprocess a source file
CBluetoothCom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/CBluetoothCom.cpp.i
.PHONY : CBluetoothCom.cpp.i

CBluetoothCom.s: CBluetoothCom.cpp.s
.PHONY : CBluetoothCom.s

# target to generate assembly for a file
CBluetoothCom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/CBluetoothCom.cpp.s
.PHONY : CBluetoothCom.cpp.s

CDevSound.o: CDevSound.cpp.o
.PHONY : CDevSound.o

# target to build an object file
CDevSound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/CDevSound.cpp.o
.PHONY : CDevSound.cpp.o

CDevSound.i: CDevSound.cpp.i
.PHONY : CDevSound.i

# target to preprocess a source file
CDevSound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/CDevSound.cpp.i
.PHONY : CDevSound.cpp.i

CDevSound.s: CDevSound.cpp.s
.PHONY : CDevSound.s

# target to generate assembly for a file
CDevSound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/CDevSound.cpp.s
.PHONY : CDevSound.cpp.s

CLocalSystem.o: CLocalSystem.cpp.o
.PHONY : CLocalSystem.o

# target to build an object file
CLocalSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/CLocalSystem.cpp.o
.PHONY : CLocalSystem.cpp.o

CLocalSystem.i: CLocalSystem.cpp.i
.PHONY : CLocalSystem.i

# target to preprocess a source file
CLocalSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/CLocalSystem.cpp.i
.PHONY : CLocalSystem.cpp.i

CLocalSystem.s: CLocalSystem.cpp.s
.PHONY : CLocalSystem.s

# target to generate assembly for a file
CLocalSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/CLocalSystem.cpp.s
.PHONY : CLocalSystem.cpp.s

localmain.o: localmain.cpp.o
.PHONY : localmain.o

# target to build an object file
localmain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/localmain.cpp.o
.PHONY : localmain.cpp.o

localmain.i: localmain.cpp.i
.PHONY : localmain.i

# target to preprocess a source file
localmain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/localmain.cpp.i
.PHONY : localmain.cpp.i

localmain.s: localmain.cpp.s
.PHONY : localmain.s

# target to generate assembly for a file
localmain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/d3.elf.dir/build.make CMakeFiles/d3.elf.dir/localmain.cpp.s
.PHONY : localmain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... d3.elf"
	@echo "... CBluetoothCom.o"
	@echo "... CBluetoothCom.i"
	@echo "... CBluetoothCom.s"
	@echo "... CDevSound.o"
	@echo "... CDevSound.i"
	@echo "... CDevSound.s"
	@echo "... CLocalSystem.o"
	@echo "... CLocalSystem.i"
	@echo "... CLocalSystem.s"
	@echo "... localmain.o"
	@echo "... localmain.i"
	@echo "... localmain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

